version: '3.4'

services:
  pji410_pg:
    image: postgres
    container_name: pji410_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: utc
      POSTGRES_USER: chuman
      POSTGRES_PASSWORD: pji410_univesp!
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/data/postgres
  # pji410_backend:
  #   build: .
  #   container_name: pji410_backend
  #   volumes:
  #     - .:/usr/app
  #   environment:
  #     TZ: utc
  #     NODE_ENV: production
  #   ports:
  #     - 3333:3333
  #   links:
  #     - pg_pji410
  #   depends_on:
  #     - pg_pji410
volumes:
  pgdata:
    driver: local
